version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "your_user"
      RABBITMQ_DEFAULT_PASS: "your_password"
    restart: always
  nginx:
    image: "nginx:latest"
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
  admin-service:
    build:
      context: ./admin-service
    ports:
      - "8086:8086"

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8080:8080"

  chat-service:
    build:
      context: ./chat-service
    ports:
      - "8085:8085"

  game-crash-service:
    build:
      context: ./game-crash-service
    ports:
      - "9003:9003"

  game-dice-service:
    build:
      context: ./game-dice-service
    ports:
      - "9000:9000"
  game-jackpot-service:
    build:
      context: ./game-jackpot-service
    ports:
      - "9006:9006"

  game-miner-service:
    build:
      context: ./game-miner-service
    ports:
      - "9002:9002"

  game-overgo-service:
    build:
      context: ./game-overgo-service
    ports:
      - "9001:9001"

  game-tower-service:
    build:
      context: ./game-tower-service
    ports:
      - "9005:9005"

  management-game-service:
    build:
      context: ./management-game-service
    ports:
      - "8084:8084"
  management-replenishment-service:
    build:
      context: ./management-replenishment-service
    ports:
      - "8082:8082"
  notification-service:
    build:
      context: ./notification-service
    ports:
      - "8087:8087"

  replenishment-service:
    build:
      context: ./replenishment-service
    ports:
      - "8081:8081"

  withdrawal-service:
    build:
      context: ./withdrawal-service
    ports:
      - "8083:8083"
volumes:
  rabbitmq_data:
